-- https://programmers.co.kr/learn/courses/30/lessons/59044
-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN ( SELECT ANIMAL_OUTS.ANIMAL_ID 
                            FROM ANIMAL_OUTS JOIN ANIMAL_INS ON ANIMAL_OUTS.ANIMAL_ID=ANIMAL_INS.ANIMAL_ID )
ORDER BY DATETIME LIMIT 3;
